### ISSUE TITLE
Doesn't handle nameless tags.

### ISSUE THREAD

**Issue by JeffHanna** [aphistic/libnbt#1]
A Minecraft terrain dat file (e.g. "World1\0\0\c.0.0.dat") begins like this:

TAG_Compound: 1 entries
{
    TAG_Compound("Level"): 11 entries
    {
        TAG_Byte_Array("Data"): [16384 bytes]
        TAG_List("Entities"): 0 entries
        {
        }
        TAG_Long("LastUpdate"): 26680
        TAG_Int("xPos"): 0
        TAG_Int("zPos"): 0

The LibNBT Query() method does not appear to handle that first nameless Compound TAG correctly. The following code snipped (IronPython) will return a value of "None".

terrain_file = LibNbt.NbtFile( )
terrain_file.LoadFile( "...\World1\0\0\c.0.0.dat", False )
x_pos  terrain_file.Query( "/Level/xPos" )

Am I missing something, especially without documentation, or is there no way for the Query() method in LibNbt to handle the structure of Minecraft chunk *.dat files?

**Comment by aphistic** [comment]
You should be able to do //Level/xPos to get the TAG_Int if I remember my implementation correctly.  The first / being the root tag, the second being the Level and the third being the tag that you want.  I'll take a look at this, I think I have this covered in a unit test but I'm not sure.

**Comment by JeffHanna** [comment]
Thanks, that does work. I thought I'd tried that. Anyway I'm back on track. Now to figure out the Blocks byte array for each chunk....

**Comment by aphistic** [comment]
Glad it worked. :)

If you run into anything else or you have a feature you'd like to see, let me know!

Also, if you're talking about finding the right byte for x, y, z in the array the formula is (or it was when I wrote libminecraft): Data[x + (y__map.Length + z)__map.Width]
