### ISSUE TITLE
Issue saving .schematic compatible files due to NbtList type.

### ISSUE THREAD

**Issue by SharkyRawr** [aphistic/libnbt#2]
Importing .schematic files saved by this library fails if the "Entities" or "TileEntities" NbtList are empty, and therefore never get a type.

I made a patch to support output for valid .schematic files even if the "Entities" and/or  "TileEntities" lists are empty: https://gist.github.com/912472
(Based on the latest commit, b5e0123146f58eb97332)

Im relatively new to the github workflow and never wrote a Nunit test before so please let me know if I made a mistake here or in the patch.

**Comment by aphistic** [comment]
Hey, thanks a lot for the patch!  I'm looking through the code trying to understand the functional differences (I'm not familiar with .schematic files).  It looks like there isn't any additional data being written for the list tag, is it possible to infer the list type without setting it explicitly in the constructor/with a separate function?  Do you have an example .schematic file that's failing that you could send to me?

**Comment by SharkyRawr** [comment]
I've been working with this, rather insufficient, definition of the file format: http://www.minecraftwiki.net/wiki/Schematic_File_Format
The issue with libnbt is that it won't set the type if the contained tag list is empty.

```
nbtfile.RootTag.Tags.Add(new NbtList("TileEntities"))
--
NbtTagType listType = Tags[0].GetTagType(); // Tags is empty, type stays 0x0
```

When saving:

```
var tagType = new NbtByte("", (byte)Type); // Type is 0x0, TAG_End as defined by NbtTagType.cs:6
tagType.WriteData(writeStream);
```

Here is a zip http://goo.gl/jWaqN with a working schematic and a one that WorldEdit isn't able to parse.
After decompression, you can see that both files differ only by one byte: 0xA in the working and 0x0 in the other.

**Comment by aphistic** [comment]
I spent some more time looking at the code and the test that you'd added and I have a version up now that I think will work for you (the test you added passes).  I also added an exception to the ListType set function so you can't set a type that's different than what's already in the list.

Let me know if this works for you!

**Comment by SharkyRawr** [comment]
Yes it works, thanks alot! :)

I have another issue saving NBT documents above a certain size but I need to make sure it's not my own code corrupting the data somehow, I will open another issue once I can pinpoint the cause.

Have a nice day.
