### ISSUE TITLE
How to read chunks in an .mca file

### ISSUE THREAD

**Issue by florentpoujol** [aphistic/libnbt#5]
Hey @aphistic 

I am trying to read an .mca (Minecraft Anvil region file) that looks like the image below in MBT Explorer.  
![mca MBT Explorer](https://dl.dropboxusercontent.com/u/51314747/mca-mbtexplorer.png)

How do I access the individual chunks ? All query "path" I have tried returned an error.
After reading the file, the RootTag is null (which explains the error, I guess).

So what should I do ?
Thanks if you can help !

Florent

**Comment by aphistic** [comment]
Hey @florentpoujol, sorry it's been... a year and I haven't gotten back to you... I didn't the issue and I don't check this project often because fNbt is probably a better option at this point.  Did you still need help or should I close this issue?

**Comment by florentpoujol** [comment]
Hey ! No, the issue don't matter anymore.
Thanks anyway !
